title: Turn a buzzer off when code is stopped by a user
hero_image: images/banner.png
description: Turn a buzzer off when code is stopped by a user
version: 4
listed: false
copyedit: false
last_tested: "2022-03-10"
steps:
  - title: Turn a buzzer off when code is stopped by a user
