title: Turn a buzzer off when code is stopped
hero_image: images/banner.png
description: buzzer-off-code-stopped description
version: 4
listed: false
copyedit: false
last_tested: "2022-03-10"
steps:
  - title: Introduction
